### PR TITLE
feature: add ability to add headers on the response

### PR DESCRIPTION
**Pull request by vim-daniel**
I think this feature is very handy especially when developing on localhost and you want to avoid CORS problems

### CODE REVIEW

**Comment by vim-daniel** [comment]
@pluma I would love for this to get approved 😬

**Comment by pluma** [comment]
Wouldn't it make more sense to support CORS explicitly? This would still pass on the `OPTIONS` requests, which the backend might be unable to handle or even reject.

**Comment by vim-daniel** [comment]
I'm not sure what you're suggesting, 
let's say i have a deployed server on domain www.a.com
and i'm writing a client in development that needs to fetch data from that server

when i'm in development my client will run in localhost, if i fetch directly from www.a.com
i receive CORS errors because my client is on localhost and the server is on www.a.com

with this feature i can proxy www.a.com and add a header that says allow localhost domain,
`OPTION` request should still work fine (from my tests i don't see any problems)

And when i deploy my client to also be on domain www.a.com then it will be in the same domain as the server so no cors problem should occur

**Comment by pluma** [comment]
If your reverse proxy is R and your backend is B and your browser tries to access R via CORS, R will currently rely on B to handle CORS directly.

As I understand your PR, the intent is to work around B not supporting CORS by adding the necessary headers to the server response from B.

But this would still require B to be able to handle OPTIONS requests. Or at least not return an error status code for those, which might the case for you but wouldn't necessarily work for others.

If the intent is to bolt CORS onto a proxied API server that doesn't support it, I'd rather intercept the OPTIONS requests and handle CORS within the reverse proxy itself.

That said, if your reverse proxy serves requests both for the frontend and the external API server, you don't need CORS.

E.g. you could do something like this:
```http-proxy /api=https://www.a.com 8000```
Assuming your frontend is served on port 8000 of localhost, this would proxy your frontend while also proxying your external API on a subfolder path.

**Comment by vim-daniel** [comment]
I understand what you mean,
your example worked for me 🚀

i still think this feature is handy (you're right that i used it in an abusive way) but still i think it has some potential

**Pull request closed without merging**
